version: '3'
services:
  db:
    image: mongo:3.4.5
    command: mongod --smallfiles --quiet --logpath=/dev/null --dbpath=/data/db
    volumes:
      - ./mongo_data:/data/db
  redis:
    image: redis:3.2.9-alpine
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DOCKER: "true"
    volumes:
      - .:/var/www/app/:rw
      - /var/www/app/node_modules
    ports:
      - "8080:8080"
    restart: always
  test:
    image: mhart/alpine-node:8.0.0
    working_dir: /var/www/app
    volumes:
      - .:/var/www/app
    environment:
      NODE_ENV: testing
    command:
      /bin/sh -c "./node_modules/.bin/ava test/unit/*.js"
  backend:
    build:
      context: .
      dockerfile: Dockerfile-go
    command: go run main.go
    volumes:
      - .:/var/www/app/:rw
    ports:
      - "3001:8081"
    environment:
      MONGO_URL: "db"
      REDIS_URL: "redis"
    restart: always
    links:
      - db
      - redis
